defaults: &defaults
  base_url: "http://lgapi-us.libapps.com/1.1/guides/?key="
  query_params: "&site_id=1504&sort_by=relevance&search_terms="
  loaded_link: "http://lib.guides.umd.edu/srch.php?q="
  key: ""

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
